In [1]:
# from fastbook import *
from sklearn import datasets
import seaborn as sns
import sklearn
import torch

from mean_classifier import MeanClassifier
from gradient_descent_regressor import GradientDescentRegressor
from gradient_descent_classifier import GradientDescentClassifier
import utils

# Mean Classifier

In [2]:
X_train, X_test, y_train, y_test = utils.load_mnist()

In [3]:
clf = MeanClassifier(loss='mae')
clf.fit(X_train, y_train)
clf.accuracy(X_test, y_test)

0.9514229893684387

In [4]:
clf = MeanClassifier(loss='mse')
clf.fit(X_train, y_train)
clf.accuracy(X_test, y_test)

0.9661432504653931

# Gradient Descent

In [5]:
M_TRUE = -6
C_TRUE = 0

X = torch.tensor(range(50)).reshape(50, 1).float()
y = ((X * M_TRUE) + C_TRUE).reshape(50)

g = GradientDescentRegressor(epochs=100, loss='mse', lr=1e-3)
g.fit(X, y)
print(g.weights, g.bias)

/Users/jack/projects/mnist/mnist/gradient_descent_regressor.py:8: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(preds, targets)


Parameter containing:
tensor([[-4.3216]], requires_grad=True) Parameter containing:
tensor([-47.5571], requires_grad=True)


In [6]:
g = GradientDescentRegressor(epochs=100, loss='mae', lr=1e-3)
g.fit(X, y)
print(g.weights, g.bias)

/Users/jack/projects/mnist/mnist/gradient_descent_regressor.py:11: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(preds, targets)


Parameter containing:
tensor([[-5.3012]], requires_grad=True) Parameter containing:
tensor([-0.7469], requires_grad=True)


# Classifier

In [7]:
clf = GradientDescentClassifier(epochs=10, batch_size=25)
clf.fit(X_train, y_train)
clf.accuracy(X_test, y_test)

IndexError: index 1 is out of bounds for dimension 1 with size 1

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=d3089e79-0e42-40a4-9bfd-5171fd4144aa' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>