In [1]:
# from fastbook import *
from sklearn import datasets
import seaborn as sns
import sklearn
import torch

from mean_classifier import MeanClassifier
from gradient_descent_regressor import GradientDescentRegressor
from gradient_descent_classifier import GradientDescentClassifier
import utils

# Mean Classifier

In [2]:
X_train, X_test, y_train, y_test = utils.load_mnist()

In [3]:
clf = MeanClassifier(loss='mae')
clf.fit(X_train, y_train)
clf.accuracy(X_test, y_test)

0.9514229893684387

In [7]:
clf = MeanClassifier(loss='mse')
clf.fit(X_train, y_train)
clf.accuracy(X_test, y_test)

0.9661432504653931

# Gradient Descent

In [8]:
M_TRUE = -2
C_TRUE = 0

X = torch.tensor(range(50)).reshape(50, 1).float()
y = ((X * M_TRUE) + C_TRUE).reshape(50)

g = GradientDescentRegressor(epochs=10_000, loss='mse', lr=1e-4, seed=1337)
g.fit(X, y)
print(g.weights, g.bias)

tensor([-1.9626], requires_grad=True) tensor([-1.2329], requires_grad=True)


In [9]:
g = GradientDescentRegressor(epochs=10_000, loss='mae', seed=1337)
g.fit(X, y)
print(g.weights, g.bias)

tensor([-2.0260], requires_grad=True) tensor([-0.9855], requires_grad=True)


# Classifier

In [10]:
clf = GradientDescentClassifier()
clf.fit(X_train, y_train)
clf.accuracy(X_test, y_test)

0.9617272019386292

In [15]:
torch.stack([clf.proba(X_test), 1 - clf.proba(X_test)], -1)

tensor([[1.0000e+00, 2.3842e-07],
        [1.0000e+00, 5.9605e-07],
        [9.9992e-01, 7.9513e-05],
        ...,
        [2.2152e-05, 9.9998e-01],
        [9.1948e-01, 8.0520e-02],
        [3.9532e-09, 1.0000e+00]], grad_fn=<StackBackward>)

In [12]:
1 - clf.proba(X_test)

tensor([2.3842e-07, 5.9605e-07, 7.9513e-05,  ..., 9.9998e-01, 8.0520e-02,
        1.0000e+00], grad_fn=<RsubBackward1>)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=d3089e79-0e42-40a4-9bfd-5171fd4144aa' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>